import { StyleSheet } from "react-native"
export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#a9e190",
    padding: 10,
    flexDirection: 'column',
  },
  topContainer: {
    flex: 4,
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  currencyAndButtonContainer:{
    alignItems: 'center',
    marginTop: 10,
    flexDirection: 'column',
  },
  flowerCountContainer:{
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  currencyText:{
    color: 'white',
    fontWeight: 'bold',
    fontSize: 25,
    marginRight: -10,
  },
  currencyImage: {
    width: 90,
    height: 90,
    resizeMode: 'cover',
  },
  imageContainer: {
    padding: 0,
    alignSelf: 'center',
    marginBottom: 60,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  image: {
    width: 200,
    height: 200,
    margin: 0,
    resizeMode: 'cover',
  },
  tasksView: {
    borderTopColor: 'black',
    borderTopWidth: 4,
    marginVertical: 0,
    flexGrow: 15,
    marginLeft: 10,
  },
  taskHeading: {
    marginBottom: 0,
    fontSize: 30,
    fontFamily: "Montserrat_800ExtraBold",
  },
  textInput: {
    backgroundColor: "#a9e190",
    fontSize: 20,
    height: 60,
    borderWidth: 2,
    borderRadius: 30,
    paddingHorizontal: 15,
    marginHorizontal: 'auto',
    marginBottom:10,
  },
  taskContainer: {
    paddingHorizontal: 15,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  checkboxContainer: {
    flex: 1,
  },
   checkbox: {
    width: 20,
    height: 20,
    borderRadius: 15,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkIcon: {
    color: '#a9e190',
  },
  completedTask: {
    textDecorationLine: 'line-through',
    color: '#54428e',
    fontSize: 20,
    textAlign: 'center',
    flex: 9,
  },
  normalTask: {
    fontSize: 20,
    textAlign: 'center',
    flex: 9,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    marginHorizontal: 8,
    marginTop: 10,
    borderWidth: 2,
    backgroundColor: "#8C86AA",
    zIndex: -1,
  },
  buttonText: {
    fontSize: 20,
    textAlign: 'center',
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
})
